app:
    debug: false
    host: "0.0.0.0"
    port: 6000
    threaded: true
api:
    CLIENT_API_SESSIONS: "/v1/sessions"
    CLIENT_API_DOCTORS: "/v1/doctors"
model:
    model_path: "/ceph/10646/intelligent_triage/model/model-webqa-hdf-2c.bin"
    seg_model_path: "/ceph/10646/intelligent_triage/model/cws.model"
    dict_var_path: "/ceph/10646/intelligent_triage/model/dict_var.npy"
    all_symptom_count_file_path: "/ceph/10646/intelligent_triage/model/all-symptom-count.data"
    disease_symptom_file_dir: "/ceph/10646/intelligent_triage/model/disease-symptom3.data"
    doctors_distributions_path: "/ceph/10646/intelligent_triage/model/doctors_distributions.json"
    doctors_id_path: "/ceph/10646/intelligent_triage/model/doctors_id.txt"
    symptoms_distributions_file_dir: "/ceph/10646/intelligent_triage/model/symptoms_distributions.json"
mongo:
    host: "127.0.0.1"
    port: 27017
    db_name: "intelligent_triage"